export const ON_INITIAL_LOADED = 'ON_INITIAL_LOADED';
export const TOGGLE_ABOUT_OVERLAY = 'TOGGLE_ABOUT_OVERLAY';
export const SET_FILTER = 'SET_FILTER';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const ON_YT_API_LOADED = 'ON_YT_API_LOADED';
export const SET_PAGE_LOADING = 'SET_PAGE_LOADING';
export const SET_CURSOR_VISIBILITY = 'SET_CURSOR_VISIBILITY';